collections:
- name: azure-azcollection-3.12.0.tar.gz
  version: 3.12.0
- name: google-cloud-1.10.2.tar.gz
  version: 1.10.2
- name: ansible-posix-2.1.0.tar.gz
  version: 2.1.0
- name: amazon-aws-10.1.2.tar.gz
  version: 10.1.2
- name: community-vmware-6.1.0.tar.gz
  version: 6.1.0
- name: community-general-12.1.0.tar.gz
  version: 12.1.0
- name: vmware-vmware-2.6.0.tar.gz
  version: 2.6.0
