---
validate_tls: false

# Optional URLs and token for API checks
# aap_controller_url, aap_gateway_url, aap_hub_url, aap_api_token

validate_controller_api: true
validate_gateway_api: true
validate_hub_api: true

# Minimal port checks
check_ports:
  - { host: "{{ inventory_hostname }}", port: 443 }
