#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
GROUP_VARS_DIR="${PROJECT_ROOT}/group_vars"
OUT_ALL="${GROUP_VARS_DIR}/all.yml"
OUT_VAULT_EXAMPLE="${GROUP_VARS_DIR}/vault.yml.example"

prompt() {
  local message="$1"
  local default_value="${2-}"
  local reply

  if [[ -n "${default_value}" ]]; then
    read -r -p "${message} [${default_value}]: " reply
    printf '%s' "${reply:-$default_value}"
  else
    read -r -p "${message}: " reply
    while [[ -z "${reply}" ]]; do
      read -r -p "${message}: " reply
    done
    printf '%s' "${reply}"
  fi
}

prompt_bool() {
  local message="$1"
  local default_value="$2"
  local reply

  while true; do
    read -r -p "${message} [${default_value}]: " reply
    reply="${reply:-$default_value}"
    case "${reply,,}" in
      true|false)
        printf '%s' "${reply,,}"
        return 0
        ;;
      y|yes)
        printf 'true'
        return 0
        ;;
      n|no)
        printf 'false'
        return 0
        ;;
      *)
        echo "Please enter true/false (or yes/no)."
        ;;
    esac
  done
}

prompt_topology() {
  local reply
  while true; do
    read -r -p "Deployment type (single_node/growth) [single_node]: " reply
    reply="${reply:-single_node}"
    case "${reply}" in
      single_node|growth)
        printf '%s' "${reply}"
        return 0
        ;;
      *)
        echo "Please enter 'single_node' or 'growth'."
        ;;
    esac
  done
}

confirm_overwrite() {
  local file_path="$1"
  if [[ -f "${file_path}" ]]; then
    local ans
    read -r -p "${file_path} already exists. Overwrite? [y/N]: " ans
    ans="${ans:-N}"
    case "${ans,,}" in
      y|yes) return 0 ;;
      *)
        echo "Aborted."
        exit 1
        ;;
    esac
  fi
}

echo "Generating Vault-friendly group vars for AAP migration role"
echo "Project root: ${PROJECT_ROOT}"

mkdir -p "${GROUP_VARS_DIR}"

confirm_overwrite "${OUT_ALL}"
confirm_overwrite "${OUT_VAULT_EXAMPLE}"

old_host="$(prompt "Old AAP 2.5 RPM host" "old-aap-25.example.com")"
new_host="$(prompt "New AAP 2.6 containerized host" "new-aap.example.com")"
old_installer_dir="$(prompt "Old installer directory" "/opt/ansible-automation-platform/installer")"
new_installer_dir="$(prompt "New installer directory" "/opt/ansible-automation-platform/installer")"
deployment_type="$(prompt_topology)"
controller_username="$(prompt "Controller admin username" "admin")"
validate_certs="$(prompt_bool "Validate TLS certs for API checks" "false")"
bundle_dir="$(prompt "Bundle dir path used by installer inventory" "{{ lookup('ansible.builtin.env', 'PWD') }}/bundle")"
registry_url="$(prompt "Registry URL" "registry.redhat.io")"

external_db_host="externaldb.example.org"
if [[ "${deployment_type}" == "growth" ]]; then
  external_db_host="$(prompt "External DB host for growth topology" "externaldb.example.org")"
fi

# Escape single quotes for safe single-quoted YAML output.
bundle_dir_escaped="${bundle_dir//\'/\'\'}"

cat > "${OUT_ALL}" <<EOF
---
# Generated by scripts/generate_group_vars.sh
# Role vars (strict namespace)

aap_25_to_26_migration_old_rpm_host: ${old_host}
aap_25_to_26_migration_new_container_host: ${new_host}
aap_25_to_26_migration_old_installer_dir: ${old_installer_dir}
aap_25_to_26_migration_new_installer_dir: ${new_installer_dir}
aap_25_to_26_migration_deployment_type: ${deployment_type}

aap_25_to_26_migration_controller_username: ${controller_username}
aap_25_to_26_migration_controller_password: "{{ vault_controller_admin_password }}"
aap_25_to_26_migration_validate_certs: ${validate_certs}

# Optional UX/safety flags
aap_25_to_26_migration_run_preflight: true
aap_25_to_26_migration_dry_run: true

aap_25_to_26_migration_postgresql_admin_username: postgres
aap_25_to_26_migration_postgresql_admin_password: "{{ vault_postgresql_admin_password }}"
aap_25_to_26_migration_bundle_install: true
aap_25_to_26_migration_bundle_dir: '${bundle_dir_escaped}'

aap_25_to_26_migration_registry_url: ${registry_url}
aap_25_to_26_migration_registry_username: "{{ vault_registry_user }}"
aap_25_to_26_migration_registry_password: "{{ vault_registry_password }}"

aap_25_to_26_migration_gateway_admin_password: "{{ vault_gateway_admin_password }}"
aap_25_to_26_migration_controller_admin_password: "{{ vault_controller_admin_password }}"
aap_25_to_26_migration_hub_admin_password: "{{ vault_hub_admin_password }}"
aap_25_to_26_migration_eda_admin_password: "{{ vault_eda_admin_password }}"

# Single-node defaults
aap_25_to_26_migration_gateway_pg_password: "{{ vault_gateway_pg_password }}"
aap_25_to_26_migration_controller_pg_password: "{{ vault_controller_pg_password }}"
aap_25_to_26_migration_hub_pg_password: "{{ vault_hub_pg_password }}"
aap_25_to_26_migration_eda_pg_password: "{{ vault_eda_pg_password }}"
aap_25_to_26_migration_single_node_host: "${new_host}"
aap_25_to_26_migration_redis_mode: standalone
aap_25_to_26_migration_controller_percent_memory_capacity: 0.5
aap_25_to_26_migration_hub_seed_collections: false

# Growth defaults (used when deployment_type=growth)
aap_25_to_26_migration_external_db_host: ${external_db_host}
aap_25_to_26_migration_gateway_pg_host: "{{ aap_25_to_26_migration_external_db_host }}"
aap_25_to_26_migration_gateway_pg_database: gateway
aap_25_to_26_migration_gateway_pg_username: "{{ vault_gateway_pg_username }}"
aap_25_to_26_migration_controller_pg_host: "{{ aap_25_to_26_migration_external_db_host }}"
aap_25_to_26_migration_controller_pg_database: controller
aap_25_to_26_migration_controller_pg_username: "{{ vault_controller_pg_username }}"
aap_25_to_26_migration_hub_pg_host: "{{ aap_25_to_26_migration_external_db_host }}"
aap_25_to_26_migration_hub_pg_database: hub
aap_25_to_26_migration_hub_pg_username: "{{ vault_hub_pg_username }}"
aap_25_to_26_migration_eda_pg_host: "{{ aap_25_to_26_migration_external_db_host }}"
aap_25_to_26_migration_eda_pg_database: eda
aap_25_to_26_migration_eda_pg_username: "{{ vault_eda_pg_username }}"
EOF

cat > "${OUT_VAULT_EXAMPLE}" <<'EOF'
---
# Copy this file to group_vars/vault.yml and encrypt it:
# ansible-vault encrypt group_vars/vault.yml

vault_controller_admin_password: "REPLACE_ME"
vault_postgresql_admin_password: "REPLACE_ME"

vault_registry_user: "REPLACE_ME"
vault_registry_password: "REPLACE_ME"

vault_gateway_admin_password: "REPLACE_ME"
vault_hub_admin_password: "REPLACE_ME"
vault_eda_admin_password: "REPLACE_ME"

vault_gateway_pg_username: "REPLACE_ME"
vault_gateway_pg_password: "REPLACE_ME"
vault_controller_pg_username: "REPLACE_ME"
vault_controller_pg_password: "REPLACE_ME"
vault_hub_pg_username: "REPLACE_ME"
vault_hub_pg_password: "REPLACE_ME"
vault_eda_pg_username: "REPLACE_ME"
vault_eda_pg_password: "REPLACE_ME"
EOF

cat <<EOF

Generated:
- ${OUT_ALL}
- ${OUT_VAULT_EXAMPLE}

Next steps:
1. Copy vault example: cp ${OUT_VAULT_EXAMPLE} ${GROUP_VARS_DIR}/vault.yml
2. Encrypt vault file: ansible-vault encrypt ${GROUP_VARS_DIR}/vault.yml
3. Set dry-run to false in ${OUT_ALL} when ready.
4. Run migration: ansible-playbook migrate_aap_25_to_26.yml
EOF
