---
- name: Upgrade AAP 2.6 containerized -> 2.6 OpenShift
  hosts: aap_primary
  gather_facts: true
  vars:
    stage_label: "upgrade_26_containerized_to_26_openshift"
    stage_name: "2.6_openshift"
    aap_installer_dir: "{{ aap26_openshift_installer_dir }}"
    aap_installer_inventory: "{{ aap26_openshift_installer_inventory_containerized_to_openshift }}"
    aap_installer_command: "{{ aap26_openshift_installer_command }}"

  roles:
    - role: aap_upgrade_containerized_to_openshift

- name: Write 2.6 OpenShift report (from 2.6 containerized)
  hosts: localhost
  gather_facts: false
  vars:
    stage_name: "2.6_openshift_from_26_containerized"
    report_dir: "{{ playbook_dir }}/../reports"
    snapshot_name: "{{ lookup('file', playbook_dir + '/../reports/last_snapshot_pre_26_openshift.txt', errors='ignore') | default('') | trim }}"
  roles:
    - role: migration_report