---
- name: Backup AAP 2.5 + sosreport
  hosts: aap_nodes
  gather_facts: true
  vars:
    backup_label: "2.5"
    aap_installer_dir: "{{ aap25_installer_dir }}"
    aap_installer_inventory: "{{ aap25_installer_inventory }}"

  roles:
    - role: sos_report
      vars:
        sos_extra_args: "--all-logs"

    - role: aap_backup
