---
- import_playbook: upgrade_aap_stage.yml
  vars:
    stage_label: "upgrade_26_containerized_to_27_containerized"
    stage_name: "2.7_containerized"
    aap_installer_dir: "{{ aap27_installer_dir }}"
    aap_installer_inventory: "{{ aap27_installer_inventory_containerized_to_containerized }}"
    aap_installer_command: "{{ aap27_installer_command }}"
    upgrade_role_name: "aap_installer_run"
    aap_setup_extra_args: "{{ aap27_setup_extra_args }}"
    upgrade_validate: true
    report_stage_name: "2.7_containerized_from_26_containerized"
    report_snapshot_name: "{{ lookup('file', playbook_dir + '/../reports/last_snapshot_pre_27.txt', errors='ignore') | default('') | trim }}"