---
- import_playbook: restore_aap_stage.yml
  vars:
    aap_installer_dir: "{{ aap26_installer_dir }}"
    aap_installer_inventory: "{{ aap26_installer_inventory_containerized }}"
    aap_restore_command: "{{ aap26_restore_command }}"
