---
- name: Restore AAP from a specified backup file
  hosts: aap_primary
  gather_facts: true
  vars:
    # Set these at runtime with -e or in group_vars/all.yml
    # aap_restore_from: /var/tmp/aap_migration_backups/<backupfile>
    aap_installer_dir: "{{ aap24_installer_dir }}"
    aap_installer_inventory: "{{ aap24_installer_inventory }}"
  roles:
    - role: aap_restore
