---
- name: Restore AAP backup
  hosts: aap_primary
  gather_facts: true
  vars:
    aap_installer_dir: "{{ aap_installer_dir | default('') }}"
    aap_installer_inventory: "{{ aap_installer_inventory | default('') }}"
    aap_restore_command: "{{ aap_restore_command | default(aap26_restore_command) }}"

  roles:
    - role: aap_restore